global using AwesomeAssertions;
global using Microsoft.Extensions.Logging;
global using Refit;
global using Solidtime.Api.Models;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Xunit;
